/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEcharts: typeof import('./components/baseEcharts/index.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    BaseTable: typeof import('./components/baseTable/index.vue')['default']
    BljzPie: typeof import('./components/management/quality/bljzPie.vue')['default']
    BlnrPie: typeof import('./components/management/quality/blnrPie.vue')['default']
    BlsEcharts: typeof import('./components/management/quality/blsEcharts.vue')['default']
    ChsEcharts: typeof import('./components/management/quality/chsEcharts.vue')['default']
    DailyChart: typeof import('./components/monthPlanCharts/dailyChart.vue')['default']
    Echarts: typeof import('./components/home/echarts.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElC: typeof import('element-plus/es')['ElC']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/home/index.vue')['default']
    JzChart: typeof import('./components/todayPlanCharts/jzChart.vue')['default']
    JzTable: typeof import('./components/todayPlanCharts/jzTable.vue')['default']
    LbChart: typeof import('./components/todayPlanCharts/lbChart.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    LTable: typeof import('./components/todayPlanCharts/lTable.vue')['default']
    Management: typeof import('./components/management/index.vue')['default']
    MonthChart: typeof import('./components/monthPlanCharts/monthChart.vue')['default']
    MonthMTD: typeof import('./components/monthPlanCharts/monthMTD.vue')['default']
    MonthPlanCharts: typeof import('./components/monthPlanCharts/index.vue')['default']
    MsgInfo: typeof import('./components/home/msgInfo.vue')['default']
    NlEcharts: typeof import('./components/management/progress/nlEcharts.vue')['default']
    Progress: typeof import('./components/management/progress/index.vue')['default']
    Quality: typeof import('./components/management/quality/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScsEcharts: typeof import('./components/management/progress/scsEcharts.vue')['default']
    ScxEcharts: typeof import('./components/management/progress/scxEcharts.vue')['default']
    Table: typeof import('./components/home/table.vue')['default']
    TodayPlanCharts: typeof import('./components/todayPlanCharts/index.vue')['default']
  }
}
